# ???? ?? ??
# 1. ????? ??, ??? ?? ? SpartaboardApplication ??? -> ?? ?? ??
# 2. ?? ? ?? ?? ??? ?? ?? ?? ??
# 3. ?? ?? -> ?? ?? ??
# 4. ?? ?? ?? ?? ???? ??? ?? ?? ( {...}? {? }? ??? ...? ? ?? ??? ?? ?? )
# DB_DATABASE_NAME={spartaboard};DB_PASSWORD={????};DB_PORT=3306;DB_USERNAME=root;PW_SALT=abcdef0123456789

spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${DB_PORT}/${DB_DATABASE_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

# password-encoder:
#  salt: ${PW_SALT}


# HS256 알고리즘을 사용할 것이기 때문에 256bit, 즉 32byte 이상의 secret key를 사용해야 한다.
# Base64 로 인코딩한 값 사용
jwt:
  secret:
    key: ${JWT_SECRET_KEY}